#local_pubs: [local_topics_to_register_at_foreign_master]
#foreign_pubs: [foreign_topics_to_register_at_local_master]
local_pubs: [/sim_client/sim_state1]
foreign_pubs: [/sim_dispatcher/sim_state1]

#local_services: [/gazebo/pause_physics, /gazebo/unpause_physics]
#foreign_services: [/gazebo/pause_physics, /gazebo/unpause_physics]
