#local_pubs: [local_topics_to_register_at_foreign_master]
#foreign_pubs: [foreign_topics_to_register_at_local_master]
local_pubs: [
  /result1,
  /base_controller/command
]
foreign_pubs: [
  /goal1,
  /base_controller/state,
  /gazebo/model_states, 
  /move_base/cancel,
  /move_base/feedback,
  /move_base/goal,
  /move_base/result,
  /move_base/status
]

local_services: [/gazebo/pause_physics, /gazebo/unpause_physics]
foreign_services: [/gazebo/pause_physics, /gazebo/unpause_physics]

